services:
  upload_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: upload_service
    restart: always
    env_file:
      - .env
    environment:
      - DEBUG=${DEBUG}
      - WORKER_URL=${WORKER_URL}
      - VIDEO_UPLOAD_NOTIFY_URL=${VIDEO_UPLOAD_NOTIFY_URL}
      - ANALYSIS_SERVICE_URL=${ANALYSIS_SERVICE_URL}
      - SECRET_KEY=${SECRET_KEY}
    ports:
    - "8050:8050"