name: Django CI/CD

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ main, develop ]

env:
  DEBUG: True
  DB_ENGINE: django.db.backends.postgresql
  ALLOWED_HOSTS: localhost,127.0.0.1
  POSTGRES_HOST: localhost
  POSTGRES_PORT: 5440
  R2_ACCESS_TOKEN: ${{ secrets.R2_ACCESS_TOKEN }}
  R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
  

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Ejecutar pruebas Django con base de datos en memoria

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
       
      - name: Print Services
        run: service --status-all

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install django djangorestframework pytest pytest-django psycopg2-binary

      - name: Run Django migrations
        run: |
          echo "Ejecutando migraciones..."
          python manage.py migrate --noinput

      - name: Run Django tests
        run: |
          echo "Ejecutando tests con pytest..."
          python manage.py test